{"uuid": "2ef341aa-0279-462b-933f-156ff34c821f", "children": ["6ce7ed41-d0e1-40c5-a145-a8d28d3f53a8"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1746169757197, "stop": 1746169757197}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/Student-App-Web/Test/conftest.py\", line 69, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1746169758431, "stop": 1746169758433}], "start": 1746169757196, "stop": 1746169758433}