{"uuid": "52f9c273-68fd-4e98-948d-3cfa9d76a752", "children": ["6f6f6f3b-f5fe-42ed-bfcd-8ff9106f6d36"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1747203608876, "stop": 1747203608876}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/Student-App-Web/Test/conftest.py\", line 69, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1747205554585, "stop": 1747205554585}], "start": 1747203608876, "stop": 1747205554585}