{"uuid": "90462892-19b8-44ec-bb6c-0c5b25add9ce", "children": ["53687b9f-50fd-4a53-bd98-549d7b20b33c"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1747203585129, "stop": 1747203585129}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n0   chromedriver                        0x0000000104c843bc cxxbridge1$str$ptr + 2829900\n1   chromedriver                        0x0000000104c7c684 cxxbridge1$str$ptr + 2797844\n2   chromedriver                        0x00000001047b9e30 cxxbridge1$string$len + 89744\n3   chromedriver                        0x00000001047f4858 cxxbridge1$string$len + 329912\n4   chromedriver                        0x000000010481cc28 cxxbridge1$string$len + 494728\n5   chromedriver                        0x000000010481bf30 cxxbridge1$string$len + 491408\n6   chromedriver                        0x000000010478ab00 chromedriver + 92928\n7   chromedriver                        0x0000000104c487e0 cxxbridge1$str$ptr + 2585200\n8   chromedriver                        0x0000000104c4bab0 cxxbridge1$str$ptr + 2598208\n9   chromedriver                        0x0000000104c29db4 cxxbridge1$str$ptr + 2459716\n10  chromedriver                        0x0000000104c4c328 cxxbridge1$str$ptr + 2600376\n11  chromedriver                        0x0000000104c1b640 cxxbridge1$str$ptr + 2400464\n12  chromedriver                        0x0000000104788d9c chromedriver + 85404\n13  dyld                                0x000000018325a0e0 start + 2360\n\n", "trace": "  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/Student-App-Web/Test/conftest.py\", line 70, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"Screenshot\", attachment_type=AttachmentType.PNG)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1747203606997, "stop": 1747203607195}], "start": 1747203585129, "stop": 1747203607195}