{"uuid": "f7401c11-4735-425b-951b-7baa7a247e06", "children": ["bc0e3770-99ed-4bf0-86af-9d2540ddc8d5"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1747040560943, "stop": 1747040560943}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lekhraj/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/Student-App-Web/Test/conftest.py\", line 69, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1747040561699, "stop": 1747040561700}], "start": 1747040560943, "stop": 1747040561700}